# Generated by Django 2.2.1 on 2019-07-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_soil', models.IntegerField()),
                ('temp_room', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('moisture', models.IntegerField()),
                ('lux', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
