# Generated by Django 2.2.1 on 2019-07-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='lux',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='moisture',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='temp_room',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='temp_soil',
            field=models.FloatField(),
        ),
    ]
