# Generated by Django 2.2.1 on 2019-07-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20190705_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='timestamp',
            field=models.DateTimeField(verbose_name='The time/date this data was recorded'),
        ),
    ]
