# Generated by Django 2.2.1 on 2019-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190705_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_data',
            name='sensor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
