# Generated by Django 2.2.1 on 2019-09-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_sensor_data_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_data',
            name='full',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor_data',
            name='heat_index',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor_data',
            name='ir',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor_data',
            name='visible',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
